markdown_extensions:
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - tables

plugins:
  - canicve:
      filename: index.md
  - search:
      separator: '[\s\-\.]+'
  - tags:
      css_name: ""
  - minify:
      minify_html: true
  - github-contributors:
      repository: canicve/canicve.com

repo_url: https://github.com/canicve/canicve
repo_name: CanICVE.com

site_name: Can I CVE
site_url: https://canicve.com
site_description: "Provided a CVE number or a Linux kernel version, returns a matrix of known-to-be affected items."
site_author: ArchiMoebius
copyright: Copyright &copy; 2021 - 2022 CanICVE

theme:
  include_search_page: false
  search_index_only: true
  name: material
  custom_dir: overrides
  favicon: images/favicon.ico
  logo: images/logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.indexes # this or toc
    #- toc.integrate # seems busted when a plugin is parsing and generating its own markdown?...
    - navigation.top
  palette:
    - scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: default
      primary: grey
      accent: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  static_templates:
    - 404.html # https://squidfunk.github.io/mkdocs-material/customization/?h=404#setup-and-theme-structure

nav:
  - Home:
    - Index: 'index.md'
    - About: 'about.md'
    - Site map: 'tags.html'
  - Hero's & Legend's: 'contributors.md'
  - Get involved!: 'contribute.md'
  - Issue Tracker: 'https://github.com/canicve/canicve.com/issues'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js

extra:
  version: 2022.01.01
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/canicve