name: ci 

on:
  push:
    branches: 
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: 'x64'
      - run: pip install requests mkdocs mkdocs-material mkdocs-github-contributors-plugin mkdocs-plugin-tags mkdocs-minify-plugin mkdocs-canicve-plugin
      - run: mkdocs gh-deploy --force
